Add data management examples
sbtqa/page-factory-example pull request #6
Opened 2018-07-13 04:57 UTC by clicman

2018-07-16 09:09 UTC, PavelAlennikov requested changes

2018-07-16 09:09 UTC, PavelAlennikov commented on src/test/resources/config/application.properties
> +## File sxtension for json and properties data types
sxtension

2018-07-16 09:09 UTC, PavelAlennikov commented on src/test/resources/config/application.properties
> +data.type =json
Пробел после =

2018-07-16 09:09 UTC, PavelAlennikov commented on src/test/resources/config/application.properties
> +## Data type
Витя, а мы по типу данных не можем автоматом определять расширения файлов, которые нас интересуют?

2018-07-16 09:25 UTC, clicman commented on src/test/resources/config/application.properties
> +## Data type
Не всегда. У тебя модет быть json или jsonp, либо properties или conf.
Так что мы знаем только дефолтные, и именно поэтому стоит такой хинт как extension

2018-07-17 03:26 UTC, kosteman requested changes

2018-07-17 03:26 UTC, kosteman commented on .factorypath
> +<factorypath>
эт чё?

2018-07-17 03:26 UTC, kosteman commented on src/test/java/ru/sbtqa/tag/pagefactoryexample/CucumberTest.java
> +        tags = {"@gtest"}
здесь без тегов

2018-07-17 03:26 UTC, kosteman commented on .vscode/launch.test.json
> +                "workingDirectory": "/home/sbt-sidochenko-vv/sandbox/pfe/page-factory-example",
может что нибудь более абстрактное?

2018-07-17 03:26 UTC, kosteman commented on src/test/java/ru/sbtqa/tag/pagefactoryexample/pages/Google/SearchPage.java
> +//        search.sendKeys(Keys.ENTER);
или раскоменть или удали

2018-07-17 08:34 UTC, merged